// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBow77tBiJ2k8hb4RbPrc0d2ZzjRIgv4I0',
    appId: '1:440073669740:web:d10f3a109aa62b0b0adc49',
    messagingSenderId: '440073669740',
    projectId: 'flutter-34477',
    authDomain: 'flutter-34477.firebaseapp.com',
    databaseURL: 'https://flutter-34477-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-34477.firebasestorage.app',
    measurementId: 'G-H1EVJEBGPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD01H9IYHDb8oE7DCr60Fw9ppKxkdRW5a4',
    appId: '1:440073669740:android:45077a9eea523ff20adc49',
    messagingSenderId: '440073669740',
    projectId: 'flutter-34477',
    databaseURL: 'https://flutter-34477-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-34477.firebasestorage.app',
  );
}
